CREATE DATABASE KIPSTER;
USE KIPSTER;

CREATE TABLE HOSTS(
	ID int NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	IPADDRESS VARCHAR(50) NOT NULL,
	UP BOOLEAN NOT NULL DEFAULT TRUE,
	DOWNTIME DATETIME NULL DEFAULT NULL,
	ALERTSENT BOOLEAN NOT NULL DEFAULT FALSE,
	ALERTTIME int(3) NULL DEFAULT 5,
	PRIMARY KEY (ID)
);

CREATE TABLE CARRIERS(
	CARRIERNAME VARCHAR(255) NOT NULL,
	CARRIEREMAIL VARCHAR(255) NOT NULL,
	PRIMARY KEY (CARRIERNAME)
);

CREATE TABLE HOSTRELATIONS(
	ID int NOT NULL,
	PARENT int NOT NULL,
	CONSTRAINT PK_HOSTRELATIONS PRIMARY KEY (ID,PARENT),
	FOREIGN KEY (ID) REFERENCES HOSTS(ID) ON DELETE CASCADE,
	FOREIGN KEY (PARENT) REFERENCES HOSTS(ID) ON DELETE CASCADE
);

CREATE TABLE PEOPLES(
	ID int NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PHONENUMBER BIGINT NULL,
	EMAIL VARCHAR(255) NULL,
	CARRIER VARCHAR(255) NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CARRIER) REFERENCES CARRIERS(CARRIERNAME) ON DELETE CASCADE
);

CREATE TABLE ALERTS(
	HOSTSID int NOT NULL,
	PEOPLESID int NOT NULL,
	TEXT BOOLEAN NOT NULL,
	CONSTRAINT PK_ALERTS PRIMARY KEY (HOSTSID,PEOPLESID),
	FOREIGN KEY (HOSTSID) REFERENCES HOSTS(ID) ON DELETE CASCADE,
	FOREIGN KEY (PEOPLESID) REFERENCES PEOPLES(ID) ON DELETE CASCADE
);

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('T-Mobile', '@tmomail.net');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('AT&T', '@txt.att.net');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('Verizon', '@vtext.com');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('Sprint', '@messaging.sprintpcs.com');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('Alltel', '@message.alltel.com');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('Boost', '@myboostmobile.com');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('U.S. Cellular', '@email.uscc.net');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('Virgin Mobile', '@vmobl.com');

INSERT INTO CARRIERS (CARRIERNAME, CARRIEREMAIL)
VALUES ('Republic Wireless', '@text.republicwireless.com');
